(in-package :clorb)
(idef-definitions
  (DEFINE-MODULE "IOP" NIL
    (DEFINE-TYPE "ProfileId" ULONG)
    (DEFINE-CONSTANT "TAG_INTERNET_IOP" "ProfileId" 0)
    (DEFINE-CONSTANT "TAG_MULTIPLE_COMPONENTS" "ProfileId" 1)
    (DEFINE-STRUCT "TaggedProfile" (("tag" "ProfileId") ("profile_data" (sequence OCTET 0))))
    (DEFINE-STRUCT "IOR" (("type_id" STRING) ("profiles" (sequence "TaggedProfile" 0))))
    (DEFINE-TYPE "ComponentId" ULONG)
    (DEFINE-STRUCT "TaggedComponent"
      (("tag" "ComponentId") ("component_data" (sequence OCTET 0))))
    (DEFINE-TYPE "MultipleComponentProfile" (sequence "TaggedComponent" 0))
    (DEFINE-CONSTANT "TAG_ORB_TYPE" "ComponentId" 0)
    (DEFINE-CONSTANT "TAG_CODE_SETS" "ComponentId" 1)
    (DEFINE-CONSTANT "TAG_POLICIES" "ComponentId" 2)
    (DEFINE-CONSTANT "TAG_ALTERNATE_IIOP_ADDRESS" "ComponentId" 3)
    (DEFINE-CONSTANT "TAG_ASSOCIATION_OPTIONS" "ComponentId" 13)
    (DEFINE-CONSTANT "TAG_SEC_NAME" "ComponentId" 14)
    (DEFINE-CONSTANT "TAG_SPKM_1_SEC_MECH" "ComponentId" 15)
    (DEFINE-CONSTANT "TAG_SPKM_2_SEC_MECH" "ComponentId" 16)
    (DEFINE-CONSTANT "TAG_KerberosV5_SEC_MECH" "ComponentId" 17)
    (DEFINE-CONSTANT "TAG_CSI_ECMA_Secret_SEC_MECH" "ComponentId" 18)
    (DEFINE-CONSTANT "TAG_CSI_ECMA_Hybrid_SEC_MECH" "ComponentId" 19)
    (DEFINE-CONSTANT "TAG_SSL_SEC_TRANS" "ComponentId" 20)
    (DEFINE-CONSTANT "TAG_CSI_ECMA_Public_SEC_MECH" "ComponentId" 21)
    (DEFINE-CONSTANT "TAG_GENERIC_SEC_MECH" "ComponentId" 22)
    (DEFINE-CONSTANT "TAG_JAVA_CODEBASE" "ComponentId" 25)
    (DEFINE-CONSTANT "TAG_COMPLETE_OBJECT_KEY" "ComponentId" 5)
    (DEFINE-CONSTANT "TAG_ENDPOINT_ID_POSITION" "ComponentId" 6)
    (DEFINE-CONSTANT "TAG_LOCATION_POLICY" "ComponentId" 12)
    (DEFINE-CONSTANT "TAG_DCE_STRING_BINDING" "ComponentId" 100)
    (DEFINE-CONSTANT "TAG_DCE_BINDING_NAME" "ComponentId" 101)
    (DEFINE-CONSTANT "TAG_DCE_NO_PIPES" "ComponentId" 102)
    (DEFINE-CONSTANT "TAG_DCE_SEC_MECH" "ComponentId" 103) 
    (DEFINE-TYPE "ServiceId" ULONG)
    (DEFINE-STRUCT "ServiceContext"
      (("context_id" "ServiceId") ("context_data" (sequence OCTET 0))))
    (DEFINE-TYPE "ServiceContextList" (sequence "ServiceContext" 0))
    (DEFINE-CONSTANT "TransactionService" "ServiceId" 0)
    (DEFINE-CONSTANT "CodeSets" "ServiceId" 1)
    (DEFINE-CONSTANT "ChainBypassCheck" "ServiceId" 2)
    (DEFINE-CONSTANT "ChainBypassInfo" "ServiceId" 3)
    (DEFINE-CONSTANT "LogicalThreadId" "ServiceId" 4)
    (DEFINE-CONSTANT "BI_DIR_IIOP" "ServiceId" 5)
    (DEFINE-CONSTANT "SendingContextRunTime" "ServiceId" 6)
    (DEFINE-CONSTANT "INVOCATION_POLICIES" "ServiceId" 7)
    (DEFINE-CONSTANT "FORWARDED_IDENTITY" "ServiceId" 8)
    (DEFINE-CONSTANT "UnknownExceptionInfo" "ServiceId" 9)))
